### ISSUE TITLE
Examples in README don't work

### ISSUE THREAD

**Issue by bkohrn** [myriad-opensource/samwell#4]
The first example in the readme gives me an error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-1811645e035b> in <module>
----> 1 with sam.writer("my-output-file.bam") as out_bam:
      2     with sam.reader("myfile.bam") as in_bam:
      3         for read in fp:
      4             if read.is_paired:
      5                 out_bam.write(read)

TypeError: writer() missing 1 required positional argument: 'header'
```

After this is dealt with (a simple matter of reversing the "with" calls and passing the header from the reader to the writer), the next error is `NameError: name 'fp' is not defined`.    This can be fixed by changing `fp` to `in_bam`.  After these two changes, the code runs.  My final code looks like: 
```
from samwell import sam
 with sam.reader("myfile.bam") as in_bam:
    with sam.writer("my-output-file.bam", in_bam.header) as out_bam:
        for read in in_bam:
            if read.is_paired:
                out_bam.write(read)
```

In the section on realigning fastqs, the example also fails.    
1. `from samwell import bwa_mem` produces an error; this should be `from samwell.sam import bwa_mem` (I tested this one)
2. The same issue from before about `sam.writer` missing a header, fixed the same way (except here the with statements don't need reversing)
3. `NameError: name 'clip_specific_reads' is not defined`.  I can't seem to find this function in the code for samwell, so I have no idea how to fix this.
4. Unless I misread the code, `bwa_mem.align` requires a path to the bwa-prepared reference genome, which doesn't seem to be invoked anywhere.

**Comment by nh13** [comment]
@bkohrn thank-you for walking through the examples.  I have a PR open to fix these, you can also see examples in the module docs.
